version: "3.7"

services:
  nginx:
    image: nginx:1.24.0
    ports:
      - 80:80
    networks:
      - nginx_django
    volumes:
      - media_volume:/data/media/
      - static_volume:/data/static/
      - /home/ubuntu/techit/nginx.conf:/etc/nginx/nginx.conf

  django:
    image: techitdjango:0.5
    networks:
      - nginx_django
    volumes:
      - media_volume:/home/techit/media/
      - static_volume:/home/techit/staticfiles/
    secrets:
      - MARIADB_USER
      - MARIADB_PASSWORD
      - MARIADB_ROOT_PASSWORD
      - MARIADB_DATABASE

  mariadb:
    image: mariadb:11.0
    networks:
      - nginx_django
    volumes:
      - mariadb_volume:/var/lib/mysql/
    environment:
      MARIADB_USER_FILE: django
      MARIADB_PASSWORD_FILE: password1234
      MARIADB_ROOT_PASSWORD_FILE: password1234
      MARIADB_DATABASE_FILE: mariadb
    secrets:
      - MARIADB_USER
      - MARIADB_PASSWORD
      - MARIADB_ROOT_PASSWORD
      - MARIADB_DATABASE


networks:
  nginx_django:

volumes:
  media_volume:
  static_volume:
  mariadb_volume:

secrets:
  MARIADB_USER:
    external: true
  MARIADB_PASSWORD:
    external: true
  MARIADB_ROOT_PASSWORD:
    external: true
  MARIADB_DATABASE:
    external: true
